services:
  - type: web
    name: nanny-backend
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    staticPublishPath: public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://nanny-backend-pk2s.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0i7ccjuibrs73a13afg-a.frankfurt-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: nanny_bear_db
      - key: DB_USERNAME
        value: nanny_bear_db_user
      - key: DB_PASSWORD
        value: YFr7Ecag5OPu5KrdN2eyaMbojkfnPPvo
      - key: FILESYSTEM_DRIVER
        value: s3
      - key: AWS_ACCESS_KEY_ID
        value: false
      - key: AWS_SECRET_ACCESS_KEY
        value: false
      - key: AWS_DEFAULT_REGION
        value: eu-north-1
      - key: AWS_BUCKET
        value: nanny-bear-media-bucket

